### ISSUE TITLE
Some definitions are not fully parsed.

### ISSUE THREAD

**Issue by yesapple** [emfomy/ehownet#5]
eg1.
cid : 1690, pid : 127, label : plant|植物, 
defn :  {animate|生物:ability({SelfMove|自移})={least|無}}

![parse2](https://user-images.githubusercontent.com/93376355/139415595-ba0c8d10-b6ca-475a-b790-fa0ab37af015.png)

`={least|無} is missing.`

---

eg2.
cid : 3084, pid : 556,  label : 圓錐|cone, 
defn :  {cubic|體:shape({BasePart|底部})={round|圓},shape({TopPart|頂端})={pointed|尖}}

![parse](https://user-images.githubusercontent.com/93376355/139412220-ff6666f9-011c-404c-82eb-48e8facc7357.png)

```
={round|圓} is missing.
= {pointed|尖}  is missing.
```

---
Most definitions witch match regex "\\)\\=" are the same.

**Comment by emfomy** [comment]
Fixed in 3.0.2
